import {ELECTRIC_BLUE, ERROR_RED, SUCCESS_GREEN} from '../../design/theme';

export const TRANSACTION_COLOR = {
  INCOME: SUCCESS_GREEN,
  EXPENSE: ERROR_RED,
  INVESTMENT: ELECTRIC_BLUE,
  LENDING: ELECTRIC_BLUE,
};
